# GET http://localhost:3000/api/v1/todos?limit=2&offset=0

# GET http://localhost:3000/api/v1/todos/7a970b3c-383f-4343-a31a-f465df9e1ba9

# POST http://localhost:3000/api/v1/todos
# content-type: application/json

# {
#     "title": "task 10",
#     "completed": false
# }

# PATCH  http://localhost:3000/api/v1/todos/7a970b3c-383f-4343-a31a-f465df9e1ba9

# DELETE  http://localhost:3000/api/v1/todos/7a970b3c-383f-4343-a31a-f465df9e1ba9