GET http://localhost:8080/api/v1/todos?limit=2&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljNjk3M2VmLWM3ZTktNDlhNS05MmJkLWRiM2Q0ZDZiODVjYSIsImlhdCI6MTY0OTIyOTkwNywiZXhwIjoxNjQ5MjMzNTA3fQ.c6eAVFLltgBXeR5zGMULEzJFM0eynM3BVDBEdyqn3RQ

# GET http://localhost:8080/api/v1/todos/7a970b3c-383f-4343-a31a-f465df9e1ba9

# POST http://localhost:8080/api/v1/todos
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljNjk3M2VmLWM3ZTktNDlhNS05MmJkLWRiM2Q0ZDZiODVjYSIsImlhdCI6MTY0OTIyOTkwNywiZXhwIjoxNjQ5MjMzNTA3fQ.c6eAVFLltgBXeR5zGMULEzJFM0eynM3BVDBEdyqn3RQ
# content-type: application/json

# {
#     "title": "task 10",
#     "completed": false
# }

# PATCH  http://localhost:8080/api/v1/todos/7a970b3c-383f-4343-a31a-f465df9e1ba9

# DELETE  http://localhost:8080/api/v1/todos/7a970b3c-383f-4343-a31a-f465df9e1ba9